apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: idpbuilder
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  # configure controller-manager bind address
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0 #Disable localhost binding
  # configure etcd metrics listen address
  etcd:
    local:
      extraArgs:
        listen-metrics-urls: http://0.0.0.0:2381
  # configure scheduler bind address
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0  #Disable localhost binding
- |-
  kind: KubeProxyConfiguration
  # configure proxy metrics bind address
  metricsBindAddress: 0.0.0.0
nodes:
- role: control-plane
  labels:
    ingress-ready: "true"
  extraPortMappings:
  - containerPort: 443
    hostPort: 8443
    protocol: TCP
  - containerPort: 32222
    hostPort: 32222
    protocol: TCP

# ------------------------- storage:nfs  -------------------------
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "scheduler.raftech.io/node-category=nfs-server,topology.kubernetes.io/zone=eu-west-1a"

# ------------------------- database node(s)  -------------------------
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "scheduler.raftech.io/node-category=database,topology.kubernetes.io/zone=eu-west-1a"

# ------------------------- worker node(s)  -------------------------
- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "scheduler.raftech.io/node-category=worker,topology.kubernetes.io/zone=eu-west-1a"

- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "scheduler.raftech.io/node-category=worker,topology.kubernetes.io/zone=eu-west-1b"

- role: worker
  kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "scheduler.raftech.io/node-category=worker,topology.kubernetes.io/zone=eu-west-1c"                               
