kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager 
    targetRevision: v1.17.2
    helm:
      releaseName: cert-manager
      valueFiles:
      - $values/value-files/values.yaml
  - repoURL: cnoe://repository-data
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  syncPolicy:
    syncOptions:
    - Replace=true
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 30
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s

