kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: grafana-operator
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: ghcr.io/grafana/helm-charts
    chart: grafana-operator
    targetRevision: v5.18.0
    helm:
      releaseName: grafana-operator
      valueFiles:
      - $values/value-files/values.yaml
  - repoURL: cnoe://repository-data
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana-operator
  syncPolicy:
    syncOptions:
    - Replace=true
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 30
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s